CREATE TABLE admin (admin_id int(10) NOT NULL AUTO_INCREMENT, name varchar(20) NOT NULL, email varchar(30) NOT NULL, admin_pass varchar(30) NOT NULL, PRIMARY KEY (admin_id));
CREATE TABLE customer (customer_id int(10) NOT NULL AUTO_INCREMENT, name varchar(30) NOT NULL, address varchar(255) NOT NULL, email varchar(30) NOT NULL, `phone no` varchar(255) NOT NULL, customer_pass varchar(30) NOT NULL, PRIMARY KEY (customer_id));
CREATE TABLE shop (shop_id int(10) NOT NULL AUTO_INCREMENT, name varchar(30) NOT NULL, address varchar(255) NOT NULL, locationLocation_id int(10) NOT NULL, PRIMARY KEY (shop_id));
CREATE TABLE medicine (medicine_id int(10) NOT NULL AUTO_INCREMENT, Medicine_name varchar(30) NOT NULL, catagory varchar(30) NOT NULL, catagorycatagory_id int(11) NOT NULL, price double NOT NULL, `expire date` date NOT NULL, `company name` varchar(30) NOT NULL, `mfg date` date NOT NULL, `pre order` binary(1), PRIMARY KEY (medicine_id));
CREATE TABLE location (Location_id int(10) NOT NULL AUTO_INCREMENT, city varchar(30) NOT NULL, `postal code` varchar(30) NOT NULL, PRIMARY KEY (Location_id));
CREATE TABLE `order` (order_id int(10) NOT NULL AUTO_INCREMENT, `order date` date NOT NULL, `order time` time NOT NULL, `delivery date` date NOT NULL, `dalivery time` time NOT NULL, `pre order` binary(1), customercustomer_id int(10) NOT NULL, `delivery mandeliveryman_id` int(10) NOT NULL, shopshop_id int(10) NOT NULL, status varchar(30) NOT NULL, prescription varchar(255) NOT NULL, cost double NOT NULL, `estimated date` date NOT NULL, `estimated time` time NOT NULL, PRIMARY KEY (order_id));
CREATE TABLE `delivery man` (deliveryman_id int(10) NOT NULL AUTO_INCREMENT, deliveryman_name varchar(30) NOT NULL, `phone no` varchar(255) NOT NULL, dm_pass varchar(30) NOT NULL, PRIMARY KEY (deliveryman_id));
CREATE TABLE shop_admin (shopshop_id int(10) NOT NULL, adminadmin_id int(10) NOT NULL, PRIMARY KEY (shopshop_id, adminadmin_id));
CREATE TABLE `admin_delivery man` (adminadmin_id int(10) NOT NULL, `delivery mandeliveryman_id` int(10) NOT NULL, PRIMARY KEY (adminadmin_id, `delivery mandeliveryman_id`));
CREATE TABLE shop_medicine (shopshop_id int(10) NOT NULL, medicinemedicine_id int(10) NOT NULL, quantity double NOT NULL, PRIMARY KEY (shopshop_id, medicinemedicine_id));
CREATE TABLE customer_medicine (customercustomer_id int(10) NOT NULL, medicinemedicine_id int(10) NOT NULL, PRIMARY KEY (customercustomer_id, medicinemedicine_id));
CREATE TABLE shop_customer (shopshop_id int(10) NOT NULL, customercustomer_id int(10) NOT NULL, PRIMARY KEY (shopshop_id, customercustomer_id));
CREATE TABLE payment (payment_id int(11) NOT NULL AUTO_INCREMENT, Status binary(1) NOT NULL, orderorder_id int(10) NOT NULL, shopshop_id int(10) NOT NULL, `delivery mandeliveryman_id` int(10) NOT NULL, `payment date` date NOT NULL, `payment time` time NOT NULL, PRIMARY KEY (payment_id));
CREATE TABLE catagory (catagory_id int(11) NOT NULL AUTO_INCREMENT, catagory_name varchar(30) NOT NULL, PRIMARY KEY (catagory_id));
ALTER TABLE shop_admin ADD CONSTRAINT FKshop_admin405703 FOREIGN KEY (shopshop_id) REFERENCES shop (shop_id);
ALTER TABLE shop_admin ADD CONSTRAINT FKshop_admin842177 FOREIGN KEY (adminadmin_id) REFERENCES admin (admin_id);
ALTER TABLE `admin_delivery man` ADD CONSTRAINT FKadmin_deli495687 FOREIGN KEY (adminadmin_id) REFERENCES admin (admin_id);
ALTER TABLE `admin_delivery man` ADD CONSTRAINT FKadmin_deli331431 FOREIGN KEY (`delivery mandeliveryman_id`) REFERENCES `delivery man` (deliveryman_id);
ALTER TABLE shop ADD CONSTRAINT FKshop455944 FOREIGN KEY (locationLocation_id) REFERENCES location (Location_id);
ALTER TABLE shop_medicine ADD CONSTRAINT FKshop_medic555493 FOREIGN KEY (shopshop_id) REFERENCES shop (shop_id);
ALTER TABLE shop_medicine ADD CONSTRAINT FKshop_medic786077 FOREIGN KEY (medicinemedicine_id) REFERENCES medicine (medicine_id);
ALTER TABLE `order` ADD CONSTRAINT FKorder450437 FOREIGN KEY (customercustomer_id) REFERENCES customer (customer_id);
ALTER TABLE `order` ADD CONSTRAINT FKorder532844 FOREIGN KEY (shopshop_id) REFERENCES shop (shop_id);
ALTER TABLE customer_medicine ADD CONSTRAINT FKcustomer_m430660 FOREIGN KEY (customercustomer_id) REFERENCES customer (customer_id);
ALTER TABLE customer_medicine ADD CONSTRAINT FKcustomer_m282483 FOREIGN KEY (medicinemedicine_id) REFERENCES medicine (medicine_id);
ALTER TABLE `order` ADD CONSTRAINT FKorder429435 FOREIGN KEY (`delivery mandeliveryman_id`) REFERENCES `delivery man` (deliveryman_id);
ALTER TABLE shop_customer ADD CONSTRAINT FKshop_custo534682 FOREIGN KEY (shopshop_id) REFERENCES shop (shop_id);
ALTER TABLE shop_customer ADD CONSTRAINT FKshop_custo452275 FOREIGN KEY (customercustomer_id) REFERENCES customer (customer_id);
ALTER TABLE payment ADD CONSTRAINT FKpayment383348 FOREIGN KEY (orderorder_id) REFERENCES `order` (order_id);
ALTER TABLE payment ADD CONSTRAINT FKpayment221425 FOREIGN KEY (shopshop_id) REFERENCES shop (shop_id);
ALTER TABLE payment ADD CONSTRAINT FKpayment853574 FOREIGN KEY (`delivery mandeliveryman_id`) REFERENCES `delivery man` (deliveryman_id);
ALTER TABLE medicine ADD CONSTRAINT FKmedicine430803 FOREIGN KEY (catagorycatagory_id) REFERENCES catagory (catagory_id);
